# Generated by Django 5.2.7 on 2025-12-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor'), ('coordinador', 'Coordinador'), ('administrador', 'Administrador')], max_length=20),
        ),
    ]
