# Generated by Django 5.2.7 on 2025-11-05 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(limit_choices_to={'rol': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
